/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adip.interfazsai;

import com.adip.interfazsai.clientRest.RequestUtil;
import com.adip.interfazsai.models.Boleta;
import com.adip.interfazsai.models.Lote;
import com.adip.interfazsai.models.Token;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.ws.rs.core.Response;
import jdk.nashorn.internal.objects.NativeArray;
import org.apache.storm.shade.org.apache.commons.codec.binary.Base64;

/**
 *
 * @author enrique
 */
public class Home extends javax.swing.JFrame {
    Token webToken = null;
    Lote[] lotes = null;
    String path = System.getProperty("user.home") + "//files";

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(Token token, Lote[] lotes){
        this.webToken = token;
        this.lotes = lotes;
        initComponents();
    }
    
    public String[] getArrayNamesLotes() {
        String names[] = new String[this.lotes.length];
        for (int i = 0; i < names.length; i++) {
            names[i] = this.lotes[i].getNombre();
            System.out.println("names[i]" + names[i]);
        }
        return names;
    }
    
    public Lote getLoteByName(String name) {
        Lote loteResponse = new Lote();
        for (Lote lote : this.lotes) {
            if (lote.getNombre().equals(name)) {
                loteResponse = lote;
            }
        }
        return loteResponse;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numDocsField = new javax.swing.JTextField();
        sendDocsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectLotes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        numDocsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDocsFieldActionPerformed(evt);
            }
        });

        sendDocsBtn.setBackground(new java.awt.Color(72, 168, 62));
        sendDocsBtn.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        sendDocsBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendDocsBtn.setText("Enviar Documentos");
        sendDocsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sendDocsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendDocsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el lote");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setText("# de documentos");

        selectLotes.setModel(new javax.swing.DefaultComboBoxModel(this.getArrayNamesLotes()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(selectLotes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sendDocsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 171, Short.MAX_VALUE))
                            .addComponent(numDocsField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(selectLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(numDocsField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(sendDocsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numDocsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDocsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDocsFieldActionPerformed

    private void sendDocsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendDocsBtnActionPerformed
        // TODO add your handling code here:
        String numDocsString = numDocsField.getText();
        if (!numDocsString.equals("")) {
            int numDocs = Integer.parseInt(numDocsString);
            File folder = new File(this.path);
            String[] nameFiles = folder.list();
            List<String> nameFilesList = Arrays.asList(nameFiles);
            Collections.sort(nameFilesList);
            if (nameFilesList.size() == numDocs * 2) {
                String error = "";
                String webToken = "Bearer " + this.webToken.getAccess();
                String seleccion = selectLotes.getSelectedItem().toString();
                Lote loteSelect = getLoteByName(seleccion);
                System.out.println("lote id" + loteSelect.getId());
                // String dateEmision = yearField.getSelectedItem().toString() + "-" + monthField.getSelectedItem().toString() + "-" + dayField.getSelectedItem().toString();
                // Lote lote = new Lote(nameLote, dateEmision, 1);
                /* RequestUtil clientWebLote = new RequestUtil();
                Response responseLote = clientWebLote.crearLote(lote, webToken);
                Boolean loteCreado = false;
                /* Lote loteResponse = new Lote();
                switch (responseLote.getStatus()){
                    case 400:
                        error = responseLote.readEntity(String.class);
                        System.out.println("error 400" + error);
                        break;
                    case 401:
                        error = responseLote.readEntity(String.class);
                        System.out.println("error 401" + error);
                        break;
                    case 201:
                        loteResponse = responseLote.readEntity(Lote.class);
                        System.out.println("Se agrego correctamente el lote: " + loteResponse.getId());
                        loteCreado = true;
                        break;
                }*/
                // Harcodeo para prod sin endpoint de Lote
                /* Boolean loteCreado = true;
                Lote loteResponse = new Lote(nameLote, dateEmision, 1);
                loteResponse.setId(1); */
                // if (loteCreado) {
                Boolean sendFiles = true;
                error = "";
                for (int i = 0; i < nameFilesList.size() - 1; i += 2) {
                    RequestUtil clientWeb = new RequestUtil(true);
                    int j = i + 1;
                    File boletaAnverso = new File(folder.getAbsolutePath() + "//" + nameFilesList.get(i));
                    File boletaReverso = new File(folder.getAbsolutePath() + "//" + nameFilesList.get(j));
                    Boleta boleta = new Boleta(boletaAnverso, boletaReverso);
                    Response response = clientWeb.crearBoletas(boleta, loteSelect, webToken);
                    switch (response.getStatus()){
                        case 400:
                            error = response.readEntity(String.class);
                            System.out.println("error 400" + error);
                            sendFiles = false;
                            break;
                        case 401:
                            error = response.readEntity(String.class);
                            System.out.println("error 401" + error);
                            sendFiles = false;
                            break;
                        case 201:
                            boletaAnverso.delete();
                            boletaReverso.delete();
                            break;
                    }
                    if (!sendFiles) {
                        break;
                    }
                }
                if (sendFiles) {
                    JOptionPane.showMessageDialog(this, "Se subieron correctamente los archivos");
                } else {
                    // Hubo algun error en la carga de documentos
                    JOptionPane.showMessageDialog(this, error);
                }
                /* } else {
                    // No se cre correctamente el lote
                    JOptionPane.showMessageDialog(this, error);
                } */
            } else {
                if (nameFilesList.size() != numDocs * 2) {
                    JOptionPane.showMessageDialog(this, "No se escanearon completamente las boletas, favor de reintentar");
                }
            }
        } else { 
            // Validaciones de formularios
            if (numDocsString.equals("")) {
                JOptionPane.showMessageDialog(this, "Favor de ingresar el numero de documentos que se van a escanear");
            }
        }
    }//GEN-LAST:event_sendDocsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numDocsField;
    private javax.swing.JComboBox selectLotes;
    private javax.swing.JButton sendDocsBtn;
    // End of variables declaration//GEN-END:variables
}
