/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adip.interfazsai;

import com.adip.interfazsai.clientRest.RequestUtil;
import com.adip.interfazsai.models.Boleta;
import com.adip.interfazsai.models.Token;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.ws.rs.core.Response;
import org.apache.storm.shade.org.apache.commons.codec.binary.Base64;

/**
 *
 * @author enrique
 */
public class Home extends javax.swing.JFrame {
    Token webToken = null;
    String path = "/home/enrique/Documentos/projects/freelance/InterfazSAI/files";

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(Token token){
        this.webToken = token;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loteField = new javax.swing.JTextField();
        numDocsField = new javax.swing.JTextField();
        sendDocsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteFieldActionPerformed(evt);
            }
        });

        numDocsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDocsFieldActionPerformed(evt);
            }
        });

        sendDocsBtn.setText("Enviar Documentos");
        sendDocsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendDocsBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Lote");

        jLabel2.setText("# de documentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(loteField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numDocsField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(38, 38, 38)
                        .addComponent(sendDocsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendDocsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numDocsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loteFieldActionPerformed

    private void numDocsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDocsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDocsFieldActionPerformed

    private void sendDocsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendDocsBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("token: " + this.webToken.getAccess());
        String webToken = "Bearer " + this.webToken.getAccess();
        RequestUtil clientWeb = new RequestUtil(true);
        File folder = new File(this.path);
        for (final File fileEntry : folder.listFiles()) {
            if (fileEntry.isFile()) {
                System.out.println("File= " + folder.getAbsolutePath()+ "\\" + fileEntry.getName());
                /* Algoritmo para converision base64*/
                Boleta boleta = new Boleta(fileEntry, fileEntry);
                System.out.println("Objeto boleta" + boleta.getBoleta_anverso());
                Response response = clientWeb.crearBoletas(boleta, webToken);
                switch (response.getStatus()){
                    case 400:
                        String error4 = response.readEntity(String.class);
                        System.out.println("error 400" + error4);
                        JOptionPane.showMessageDialog(this, error4);
                        break;
                    case 401:
                        String error = response.readEntity(String.class);
                        System.out.println("error 401" + error);
                        JOptionPane.showMessageDialog(this, error);
                        break;
                    case 200:
                        System.out.println("Se agrego correctamente");
                        break;
                }
            }
        }
        
        /* Map<String,String> env = System.getenv();
        Set<String> keys = env.keySet();
        keys.stream().forEach((key) -> {
            System.out.println(key + " = "+env.get(key));
        });*/
        
    }//GEN-LAST:event_sendDocsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loteField;
    private javax.swing.JTextField numDocsField;
    private javax.swing.JButton sendDocsBtn;
    // End of variables declaration//GEN-END:variables
}
